class Exception:
    def getemployee_exception(self,id):
        return "ID :"+id+" does not exists in the table"
        
    
        
